### ISSUE TITLE
Feedback on page "New APIs in Java 19"

### ISSUE THREAD

**Issue by AlanBateman** [marchof/java-almanac#116]
A comment on [this page](https://javaalmanac.io/jdk/19/apidiff/18/):

Several Java APIs have been changed recently to be sealed classes. When using the "Compare" views it looks like the pages are showing the complete list of permitted classes. This includes a lot of non-accessible implementation classes. Maybe you could filter the list of permitted classes to those that are public and in exported classes, I think that would reduce the noise and make the pages more readable.

**Comment by marchof** [comment]
Hi @AlanBateman thanks for your feedback! I had the same observation but did not find a proper solution yet. Filtering referenced types by their visibility is currently not really supported by my simple diff tool.

Instead of listing all permitted subclasses I could simply give a class a "sealed" tag if it declares at least one permitted subclass.

* Pro: Very concise diff, new sealed classes can be easily spotted
* Con: Change in list if permitted subclasses is not shown

For me this is a pragmatic solution which at least gives a quick overview. WDYT?

**Comment by jnehlmeier** [comment]
What about tags `[+ sealed]` or `[- sealed]` or `[sealed: permits changed]`.

However I can already see someone asking to see the permits. Maybe opening permits in a modal view might be an option which does not cause trouble with the current list layout. So `[+ sealed]` and `[sealed: permits changed]` should be clickable then.

**Comment by marchof** [comment]
@jnehlmeier As of today these pages are statically rendered. Also it is all backed by an [API](https://editor.swagger.io/?url=https://data.javaalmanac.io/v1/openapi.yaml) which I need to consider when I do changes.

**Comment by AlanBateman** [comment]
I don't think it's useful to list permitted subclasses that aren't accessible. In the API docs you'll see it includes "(not exhaustive)" when the permitted subclasses includes subclasses that aren't part of the API. If I read your comment correctly then this is not currently feasible with the diff tool. Okay, I was just providing feedback that recent diffs have noise.  You mentioned printing "sealed" when the PermittedSubclasses attribute is present and that could be useful.
