### ISSUE TITLE
Regarding JAVAFX removal

### ISSUE THREAD

**Issue by kris9119** [marchof/java-almanac#210]
Hi,

This is a nicely compiled wiki, I see that JAVAFX removal is not mentioned in your documentation.

As per my knowledge, "JavaFX was removed from JDK since JDK 11."  Could this be validated and added in your documentation please?

Thanks
Narasimha

**Comment by marchof** [comment]
I need to do some research on this. From my understanding JavaFX was always a separate project, but some vendors decided to include it in their OpenJDK distributions over time. Any sources and references are welcome!

**Comment by nicktombeur** [comment]
I hope the following information is helpful:

JavaFX was a separate project until Java SE 7 update 6.
Since Java 8, JavaFX got the same numbering.
Java 11 and above, does not include JavaFX anymore.

According the release notes:
> The JavaFX modules have been removed from the JDK 11 release. These modules were included in earlier releases of the Oracle JDK, but not in the OpenJDK releases. The JavaFX modules will be available as a separate set of modules outside the JDK. More details are available in this white paper: [http://www.oracle.com/technetwork/java/javase/javaclientroadmapupdate2018mar-4414431.pdf](https://www.oracle.com/docs/tech/java/javaclientroadmapupdate2018mar.pdf) (PDF)
Bug ID: JDK-8198527 (not public)

From their roadmap:
> Oracle completed the re-architecture and transition of JavaFX to OpenJFX as a
stand-alone module as of Java SE 11. Oracle is also reaffirming its commitment to continue coleading and collaborating at the OpenJFX project.

Sources and references:
- [JavaFX FAQ](https://web.archive.org/web/20181029152754/https://www.oracle.com/technetwork/java/javafx/overview/faq-1446554.html) 
- [Announcement of removal ](https://web.archive.org/web/20190429062213/https://gluonhq.com/gluon-and-javafx/)
- [Release note](https://www.oracle.com/java/technologies/javase/11-relnote-issues.html)
- [Roadmap](https://www.oracle.com/technetwork/java/javase/javaclientroadmapupdatev2020may-6548840.pdf)

**Comment by marchof** [comment]
See also: https://en.wikipedia.org/wiki/JavaFX
